language: java
jdk:
- openjdk8
before_install:
- chmod +x mvnw
deploy:
  provider: heroku
  api_key:
    secure: dhCXlciAkZPBY+glFDRr6gKc2k0HqYaqgvbN4v+LhoaIPUg9yknjnG1szcRX6OtcI22R19qZCJDkxCNdLL8S5F523BZv3LG9wjU+eRzRceqe+FLP8pSU/pJ/Q79UTtE+mVNaq7pfuHTDyg9v9Un4wPlr+xTQgmH2BIiBwDgpXlAGdXTZM63sQbZrO25PhpR4wyeHMp69ndl+OtsFLez4xS0T4n4SrhbZlcBTXvTaTM5KI3To95NmPUgmjmPsePNntY04hJKH+ydzWpYJjAyMKf1UNWewnB+WFi7k0IqP6qgjBMrkMEv+mHhEqo5fUWcSzp1OynRoVwU6kEAs0+CFf81LxkmrJ1SWxVZ0gNF9e0cSZ9FLQIEwt9xN2pzOW9SPGQ1damdpNztvYLso3CWzKLn9GV/Pxy94tW79hZODJUm55vPrkjIYjZ5uHE2K5vcRwUytEFAMXG1yJwNVDmLzVi0mUICQJxrzuT4psk25kchEpE5dk3R0JCgMEP6+ITf0I/3tcVDK6+TrEacFHs0hjKuACwlTlDdzmR1jNhSrlwyJjWHSylDmvZPvosXvtyLzUuzfghxZv/nAp3TwpSVTGtzRyKEQSi38ZtgFyDqZBjQqMvem8gMlQgVYY+x3NYWM2mmsRhfwe4gQkXZj+ldmfDw7LZu5ZDBp8lGPC+e7duU=
  app: ms-timesheet-person-app-dev
  on:
    branch: master
