language: java
jdk:
- openjdk8
before_install:
- chmod +x mvnw
deploy:
  provider: heroku
  api_key:
    secure: CGSk7l+aNpoduhcou5VR6WvzXdPYZDtcNIWoW72MJkz3shm+eOlyIVBUjh8ZNUj66++ffrgFBtvuajRwirCEhREw3F4bHdGv/cWD/CJlEtUEv2JwqNGyfvUAueHWewT07yJhNhck8XcS+er6WmKvL82VkwnVv1VTsouEeNRtpDVIvPp93LUA6nykfeM51n2ptpBbNDVrhaxUcSrPgrx4mflVm2BjV8dPJxj/Nx6oQlMbj0rf16zxzuR9cJzNY4EBDO+QCadSFCBcJyUEdYejBNIGGEDdTwcLO/YRL8PrGUxfweDbrMAGU4Zwz16TNHdvTBBE1HME1r+w0DGqCPLGw6tffY7Ms8N6StM6Mr+dYKWSQ7ou4ktDTOIU+JDIeQqw/qeExF75gdihW96l1QD10avBG1p0IlKpCqaff1byg6UyvDgNXFUN2HJIw0aZ/d67/T4orGIEpS+X0wkjRQqPFB5QNaK86nkPvLC09P1rOnxRWYoSV4rL1QPo9bPJmZ9jvsu16e3K83MXHiVvKIc6NNUkA4kU3UaA9TZkd1+VVItRPnQCTT3nFkPe5mWu/bEKg3rhWShE/e1FzqBlpxbYKrw551c8jcc2Q+lENjxRnov5JtVPgqZHH4qzx5AqVLj5ek0e510WMIn4VNCH5BJznBkdYCRT5alaVAhSODl6z2c=
  app: ms-timesheet-person-app-dev
  on:
    branch: master
