server:
  port: 8081
  servlet:
    context-path: /

spring:
  application:
    name: person
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/person?createIfNotExists=true&useTimezone=true&serverTimezone=UTC
    username: root
    password: root
  jmx:
    enabled: true
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
    hibernate:
      ddl-auto: update

eureka:
  instance:
    hostname: localhost
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka