server:
  port: 8081
  servlet:
    context-path: /
    
spring:
  application:
    name: person
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://ec2-54-158-190-214.compute-1.amazonaws.com:5432/da7i9rb9iit0s8
    username: isbtmycxerlski
    password: 6528b1b8e48ad6e63384a90eaa983d5cc6c096c7b7d43d7826dc09f03e691004
  jmx:
    enabled: true
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update


eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: https://eureka-server-app-dev.herokuapp.com/eureka