CREATE TABLE PERSON(
	ID SERIAL PRIMARY KEY,
	SOCIAL_RASON VARCHAR(150),
	FIRST_NAME VARCHAR(50),
	LAST_NAME VARCHAR(50),
	NICKNAME VARCHAR(15),
	AGE INTEGER,
	DOCUMENT VARCHAR(20),
	PERSON_TYPE VARCHAR(20),
	PERSON_USER_KEY VARCHAR(150),
	CREATED_DATE TIMESTAMP,
	UPDATED_DATE TIMESTAMP,
	ADDRESS_ID INTEGER,
    CONSTRAINT FK_ADDRESS_PERSON FOREIGN KEY (ADDRESS_ID)
    REFERENCES ADDRESS(ID)
);