CREATE TABLE ADDRESS (
 	ID serial PRIMARY KEY,
	STREET VARCHAR ( 120 ) NOT NULL,
	NEIGHBORHOOD VARCHAR ( 120 ) NOT NULL,
	NUMBER INTEGER,
	COMPLEMENT VARCHAR ( 120 ) NOT NULL,
	CITY VARCHAR ( 120 ) NOT NULL,
	CEP VARCHAR (20) NOT NULL,
	REFERENCE VARCHAR(120)
);