CREATE TABLE ADDRESS(
 	ID INT(10) NOT NULL PRIMARY KEY AUTO_INCREMENT,
	STREET VARCHAR(150),
	NEIGHBORHOOD VARCHAR(150),
	NUMBER INT(5),
	COMPLEMENT VARCHAR(150),
	CITY VARCHAR(150),
	CEP VARCHAR(20),
	REFERENCE VARCHAR(120)
);